- name: ec2 provison
  hosts: localhost
  tasks:
   - name: launch ec2
 
     amazon.aws.ec2:
            key_name: csye6225-fall2020-aws
            instance_type: t2.micro
            image: ami-0d5eff06f840b45e9
            region: us-east-1
            wait: yes
            group: default
            count: 1
            vpc_subnet_id: subnet-e0803486
            assign_public_ip: yes
     register: ec2
